packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.30.1
  '@typescript-eslint/eslint-plugin': ^8.35.1
  '@typescript-eslint/parser': ^8.35.1
  eslint: ^9.30.1
  typescript-eslint: ^8.35.1
  prettier: ^3.0.0
  '@types/node': ^20.16.1
  typescript: ^5.7.3
  globals: ^15.15.0
  cross-env: ^7.0.3
  dotenv: ^16.4.7
  nodemon: ^3.1.7
  ts-node: ^10.9.2
  tsc-alias: ^1.8.10
  tsconfig-paths: 4.2.0
  discord.js: ^14.18.0
  date-fns: ^2.30.0
  mongodb: ^6.8.0
  mongoose: ^8.9.5
  '@thevoidcommunity/the-void-database': 4.1.4-beta.1
  fbit-field: 1.4.0-alpha.1c
  f-formatter: 0.3.1
  fock-logger: 4.0.1a
